import Config

# Local dev: postgres runs in Docker on port 5433
config :naturecounts, Naturecounts.Repo,
  hostname: "localhost",
  port: 5433

config :naturecounts, NaturecountsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4005],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "LHkdi3UKoLINjIBxujp5R8QNVxPPmhhHBfhC8uLiQyPO0OyCvci9gWdVqdYCGCjt",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:naturecounts, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:naturecounts, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :naturecounts, NaturecountsWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/naturecounts_web/router\.ex$",
      ~r"lib/naturecounts_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :naturecounts, dev_routes: true

# Fake cameras from pre-recorded files for development.
# Videos are in the project root's videos/ directory.
# Set CAMERAS=rtsp to use real DeepStream RTSP sources instead.
videos_dir = Path.expand("../../videos", __DIR__)

config :naturecounts, :cameras, [
  %{id: "cam1", source: {:file, Path.join(videos_dir, "cam_1.mp4")}},
  %{id: "cam2", source: {:file, Path.join(videos_dir, "cam_2.mp4")}},
  %{id: "cam3", source: {:file, Path.join(videos_dir, "cam_3.mp4")}}
]

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"
config :logger, level: :info

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
