FROM elixir:1.18-otp-27-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    nodejs \
    npm \
    build-essential \
    pkg-config \
    libsrtp2-dev \
    ca-certificates \
    libavcodec-dev \
    libavutil-dev \
    inotify-tools \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mix local.hex --force && mix local.rebar --force

EXPOSE 4005

CMD ["sh", "-c", "mix deps.get && mix ecto.setup && mix phx.server"]
